#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
#    driver-class-name: com.mysql.jdbc.Driver     #MySQL驱动包
#    url: jdbc:mysql://101.43.25.47:3306/serve_task?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: Xjh@187acb1212
server:
  port: ${task.port}

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xjh.common.bean  #所有的Entities别名类的包

#data:
#  url: jdbc:mysql://101.43.25.47:3306/serve_task?useUnicode=true&characterEncoding=utf-8&useSSL=false
#  username: root
#  password: Xjh@187acb1212
#  driverClassName: com.mysql.jdbc.Driver
#  initialSize: 5
#  minIdle: 10
#  maxActive: 15
#  maxWait: 60

